### ISSUE TITLE
no bypass help

### ISSUE THREAD

**Issue by ghost** [danny-125/Peroxide#16]
no blur? no hypixel bypai? no 3D render modules? removed all my commits because you know i coded 90% of your client? no new base? terrible visuals? why stick onto base i made? no china hat? no color picker? no scripting? danny come back i loved seeing you get mad 🙏, btw for anyone reading this, this is basically my client i coded most of it, its kinda shit but i have a new one anyway

**Comment by danny-125** [comment]
no bitches? you didnt code even 20% of the client. you couldnt even figure out how to code a number slider. I dont give 2 shits about clients anymore yet its amusing to see you come at me for no reason. Ive literally had people tell me you tried to skid Dort. You're criticizing a client that hasnt been updated for a long ass time. Plus i have no idea where you got the idea that not having a china hat module matters. I removed your commits because most of them were broken. The visuals are shit here yet when i recontinued it for like a month it actually had real visuals and bypasses. When I got your client source twice, neither times did it have any bypasses. I think the only working bypass you had was brokenlens fly, thats pathetic considering i made it 2 months before you had it. Not to mention all of the stolen code in Atlas's source. No color pickers a straight up lie as well im pretty sure i added that very soon after I added the click gui. When i recontinued it literally had all of the things you say I dont have. Given I dont care about coding childish block game cheats anymore. You can stay mad with your bypasses that hardly work. Plus let this sink in, you managed to lose friends, trust, and a lot of time over dogshit cheats.

**Comment by LeanManOffThePerc** [comment]
you dont have atlas src lmao and keep crying and only writing to make you mad

**Comment by danny-125** [comment]
ok and? i had it when your dumbass gave it to me. its old now but i still have that source

**Comment by rafalohaki** [comment]
Why
